import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import theme from '@/app/_constants/customTheme';
import Footer from "@/app/_layouts/footer";
import Header from "@/app/_layouts/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <UserProvider>
         <MantineProvider theme={theme}>
          <Header />
          <main>{children}</main>
          <Footer />
          </MantineProvider>
        </UserProvider>
      </body>
    </html>
  );
}
