version: '3.9'
services:
  db:
    image: mysql:8.0.36
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
    command: sh -c "rm -f /back/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/app
      - ./back/vendor/bundle:/back/vendor/bundle
    ports:
      - '4000:3000'
    stdin_open: true
    tty: true

    depends_on:
      - db
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - ./front:/app
    command: yarn dev -p 8000
    ports:
      - '8002:8000'
volumes:
  mysql_data:
    driver: local